name: upgradinatorr

services:
  upgradinatorr:
    image: mountaingod2/upgradinatorr:latest
    container_name: upgradinatorr
    volumes:
      - ./config:/config
    environment:
      - PUID=1000
      - PGID=1000
    command: ["-a", "radarr,sonarr"]
    restart: "no"
